import { StyleSheet } from 'react-native'

export const WHITE = '#ffffff'
export const TEAL = '#00b1b9'

export default StyleSheet.create({
  imageContain: { resizeMode: 'contain' },
  imageCover: { resizeMode: 'cover' },
  col1: { flexBasis: '8.33%', width: '100%' },
  col2: { flexBasis: '16.66%', width: '100%' },
  col3: { flexBasis: '25%', width: '100%' },
  col4: { flexBasis: '33.33%', width: '100%' },
  col5: { flexBasis: '41.66%', width: '100%' },
  col6: { flexBasis: '50%', width: '100%' },
  col7: { flexBasis: '58.33%', width: '100%' },
  col8: { flexBasis: '66.66%', width: '100%' },
  col9: { flexBasis: '75%', width: '100%' },
  col10: { flexBasis: '83.33%', width: '100%' },
  col11: { flexBasis: '91.66%', width: '100%' },
  col12: { flexBasis: '100%', width: '100%' },
  positionAbsolute: { position: 'absolute' },
  positionRelative: { position: 'relative' },
  positionFixed: { position: 'fixed' },
  top0: { top: 0 },
  bottom0: { bottom: 0 },
  left0: { left: 0 },
  right0: { right: 0 },
  container: { height: '420px' },
  flexRow: { flexDirection: 'row' },
  flexRowReverse: { flexDirection: 'row-reverse' },
  flexColumn: { flexDirection: 'column' },
  flexColumnReverse: { flexDirection: 'column-reverse' },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  flex3: { flex: 3 },
  flex4: { flex: 4 },
  flex5: { flex: 5 },
  flex6: { flex: 6 },
  flexGrow0: { flexGrow: 0 },
  flexGrow1: { flexGrow: 1 },
  flexGrowInherit: { flexGrow: 'inherit' },
  flexGrowInitial: { flexGrow: 'initial' },
  flexGrowUnset: { flexGrow: 'unset' },
  flexShrink0: { flexShrink: 0 },
  flexShrink1: { flexShrink: 1 },
  flexShrinkInherit: { flexShrink: 'inherit' },
  flexShrinkInitial: { flexShrink: 'initial' },
  flexShrinkUnset: { flexShrink: 'unset' },
  flexWrap: { flexWrap: 'wrap' },

  justifyStart: { justifyContent: 'flex-start' },
  justifyCenter: { justifyContent: 'center' },
  justifyEnd: { justifyContent: 'flex-end' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyAround: { justifyContent: 'space-around' },
  justifyEvenly: { justifyContent: 'space-evenly' },
  alignBaseline: { alignItems: 'baseline' },
  alignStart: { alignItems: 'flex-start' },
  alignCenter: { alignItems: 'center' },
  alignEnd: { alignItems: 'flex-end' },
  alignStretch: { alignItems: 'stretch' },
  row: { flexDirection: 'row', marginHorizontal: -15, width: '100%' },
  col: { paddingHorizontal: 15 },
  w25p: { width: '25%' },
  w33p: { width: '33.33%' },
  w50p: { width: '50%' },
  w67p: { width: '66.66%' },
  w75p: { width: '75%' },
  w100p: { width: '100%' },
  h100p: { height: '100%' },
  h100vh: { height: '100vh' },
  w15: { width: 15 },
  w20: { width: 20 },
  w40: { width: 40 },
  w50: { width: 50 },
  w60: { width: 60 },
  w80: { width: 80 },
  w120: { width: 120 },
  w200: { width: 200 },
  w230: { width: 230 },
  w300: { width: 300 },
  w400: { width: 400 },
  w600: { width: 600 },
  w700: { width: 700 },
  w800: { width: 800 },
  w900: { width: 900 },
  mw900: { maxWidth: 900 },
  mw1200: { maxWidth: 1200 },
  h5: { height: 5 },
  h15: { height: 15 },
  h20: { height: 20 },
  h40: { height: 40 },
  h50: { height: 50 },
  h60: { height: 60 },
  h80: { height: 80 },
  h120: { height: 120 },
  h250: { height: 250 },
  h500: { height: 500 },
  mr2: { marginRight: 2 },
  mb5: { marginBottom: 5 },
  mr5: { marginRight: 5 },
  mt5: { marginTop: 5 },
  mx5: { marginHorizontal: 5 },
  my5: { marginVertical: 5 },
  mb10: { marginBottom: 10 },
  ml10: { marginLeft: 10 },
  mr10: { marginRight: 10 },
  mt10: { marginTop: 10 },
  mx10: { marginHorizontal: 10 },
  mb15: { marginBottom: 15 },
  mr15: { marginRight: 15 },
  mt15: { marginTop: 15 },
  mx15: { marginHorizontal: 15 },
  my16: { marginVertical: 15 },
  mb20: { marginBottom: 20 },
  ml20: { marginLeft: 20 },
  mr20: { marginRight: 20 },
  mt20: { marginTop: 20 },
  my25: { marginVertical: 25 },
  mb30: { marginBottom: 30 },
  ml30: { marginLeft: 30 },
  mr30: { marginRight: 30 },
  mx30: { marginHorizontal: 30 },
  my30: { marginVertical: 30 },
  mb45: { marginBottom: 45 },
  mb60: { marginBottom: 60 },
  mb72: { marginBottom: 72 },
  mr120: { marginRight: 120 },
  mb120: { marginBottom: 120 },
  py2: { paddingVertical: 2 },
  pb5: { paddingBottom: 5 },
  pl5: { paddingLeft: 5 },
  px5: { paddingHorizontal: 5 },
  py5: { paddingVertical: 5 },
  pb10: { paddingBottom: 10 },
  pl10: { paddingLeft: 10 },
  px10: { paddingHorizontal: 10 },
  py10: { paddingVertical: 10 },
  p15: { padding: 15 },
  pb15: { paddingBottom: 15 },
  pl15: { paddingLeft: 15 },
  pr15: { paddingRight: 15 },
  pt15: { paddingTop: 15 },
  px15: { paddingHorizontal: 15 },
  py15: { paddingVertical: 15 },
  px20: { paddingHorizontal: 20 },
  py20: { paddingVertical: 20 },
  p30: { padding: 30 },
  pr30: { paddingRight: 30 },
  px30: { paddingHorizontal: 30 },
  py30: { paddingVertical: 30 },
  px45: { paddingHorizontal: 45 },
  py45: { paddingVertical: 45 },
  px60: { paddingHorizontal: 60 },
  py60: { paddingVertical: 60 },
  px100: { paddingHorizontal: 100 },
  px120: { paddingHorizontal: 120 },
  bgWhite: { backgroundColor: '#ffffff' },
  bgTeal: { backgroundColor: '#00b1b9' },
  bgTealDarker: { backgroundColor: '#009096' },
  bgWhiteDarker: { backgroundColor: '#f7f7f7' },
  bgYellow: { backgroundColor: '#ffc20e' },
  bgGray: { backgroundColor: '#dddddd' },
  bgRed: { backgroundColor: '#ff0000' },
  bgOzoRed: { backgroundColor: '#eb5b4e' },
  bgGreen: { backgroundColor: '#00ff00' },
  bgGrayLighter: { backgroundColor: '#f2f2f2' },
  bgGrayDarker: { backgroundColor: '#404040' },
  bgDarkGray: { backgroundColor: '#707070' },
  br3: { borderRadius: 3 },
  br4: { borderRadius: 4 },
  br5: { borderRadius: 5 },
  br8: { borderRadius: 8 },
  br10: { borderRadius: 10 },
  br20: { borderRadius: 20 },
  br25: { borderRadius: 25 },
  br100: { borderRadius: 100 },
  br10Left: { borderBottomLeftRadius: 10, borderTopLeftRadius: 10 },
  brLeft5: { borderTopLeftRadius: 5, borderBottomLeftRadius: 5 },
  brTop5: { borderTopLeftRadius: 5, borderTopRightRadius: 5 },
  brRight5: { borderTopRightRadius: 5, borderBottomRightRadius: 5 },
  brLeft10: { borderTopLeftRadius: 10, borderBottomLeftRadius: 10 },
  brTop10: { borderTopLeftRadius: 10, borderTopRightRadius: 10 },
  brRight10: { borderTopRightRadius: 10, borderBottomRightRadius: 10 },
  brBottom10: { borderBottomLeftRadius: 10, borderBottomRightRadius: 10 },
  brBottom20: { borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
  b1: { borderWidth: 1 },
  b1p5: { borderWidth: 1.5 },
  b2: { borderWidth: 2 },
  bBottom1: { borderBottomWidth: 1 },
  bBottom2: { borderBottomWidth: 2 },
  bBottom3: { borderBottomWidth: 3 },
  bTop1: { borderTopWidth: 1 },
  bGray: { borderColor: '#dddddd' },
  bGrayLighter: { borderColor: '#bbbbbb' },
  bDarkGray: { borderColor: '#707070' },
  bGrayDarker: { borderColor: '#657786' },
  bYellow: { borderColor: '#ffc20e' },
  bTeal: { borderColor: '#00b1b9' },
  bRed: { borderColor: '#eb5b4e' },
  bTransparent: { borderColor: 'transparent' },
  bBottomWhite: { borderBottomColor: '#ffffff' },
  bTopTransparent: { borderTopColor: 'transparent' },
  bBottomTransparent: { borderBottomColor: 'transparent' },
  bShadow: {
    shadowColor: 'rgba(0,0,0,0.20)',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  bShadowLight: {
    shadowColor: 'rgba(0,0,0,0.10)',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  bDashed: {
    borderStyle: 'dashed',
    borderColor: '#b2b2b2',
    borderRadius: 10,
    borderWidth: 2,
  },
  bSolidTeal: {
    borderStyle: 'solid',
    borderColor: '#00b1b9',
    borderRadius: 100,
    borderWidth: 2,
  },
  outlineStyleNone: { outlineStyle: 'none' },
  f10: { fontFamily: 'Lato', fontSize: 10 },
  f12: { fontFamily: 'Lato', fontSize: 12 },
  f14: { fontFamily: 'Lato', fontSize: 14 },
  f16: { fontFamily: 'Lato', fontSize: 16 },
  f18: { fontFamily: 'Lato', fontSize: 18 },
  f20: { fontFamily: 'Lato', fontSize: 20 },
  f25: { fontFamily: 'Lato', fontSize: 25 },
  f28: { fontFamily: 'Lato', fontSize: 28 },
  f35: { fontFamily: 'Lato', fontSize: 35 },
  f45: { fontFamily: 'Lato', fontSize: 45 },
  textNormal: { fontWeight: '400' },
  textBold: { fontWeight: '700' },
  textItalic: { fontStyle: 'italic' },
  textTeal: { color: '#00b1b9' },
  textYellow: { color: '#ffc20e' },
  textGrayLighter: { color: '#b2b2b2' },
  textGray: { color: '#878787' },
  textGrayDarker: { color: '#404040' },
  textRed: { color: '#eb5b4e' },
  textWhite: { color: '#ffffff' },
  textLeft: { textAlign: 'left' },
  textCenter: { textAlign: 'center' },
  textRight: { textAlign: 'right' },
  textUnderline: { textDecorationLine: 'underline' },
  overflowHidden: { overflow: 'hidden' },
  overflowVisible: { overflow: 'visible' },
  zIndex0: { zIndex: 0 },
  zIndex1: { zIndex: 1 },
  zIndex2: { zIndex: 2 },
  zIndex10: { zIndex: 10 },
  video169: {
    position: 'relative',
    paddingBottom: '56.25%',
    paddingTop: 25,
    height: 0,
    backgroundColor: '#404040',
  },
})
